name: Coverage and SonarCloud
description: Build with LLVM coverage, run tests, collect coverage, and run SonarCloud scan
inputs:
  build_preset:
    description: CMake preset to use (coverage preset expected)
    required: false
    default: coverage
  sonar_token:
    description: SonarCloud token
    required: true
runs:
  using: composite
  steps:
    - name: Test with coverage
      shell: bash
      run: |
        # If NVIDIA/self-hosted X is available, start X on :99 and use it; otherwise use Xvfb
        if [ -f /etc/X11/xorg.conf ] || command -v nvidia-smi >/dev/null 2>&1; then
          if ! pgrep -f "X :99" > /dev/null; then
            sudo X :99 -config /etc/X11/xorg.conf > /dev/null 2>&1 &
            sleep 5
          fi
          export DISPLAY=:99
          ctest --preset "${{ inputs.build_preset }}" --output-on-failure
        else
          sudo apt-get update && sudo apt-get install -y xvfb mesa-utils libgl1-mesa-dri
          xvfb-run -a env \
            LIBGL_ALWAYS_SOFTWARE=1 \
            GALLIUM_DRIVER=llvmpipe \
            MESA_GL_VERSION_OVERRIDE=4.5 \
            MESA_GLSL_VERSION_OVERRIDE=450 \
            ctest --preset "${{ inputs.build_preset }}" --output-on-failure
        fi

    - name: Merge and collect LLVM coverage
      shell: bash
      run: |
        # Find all .profraw files generated by tests
        find build/coverage -name "*.profraw" -o -name "default.profraw" > profraw_files.txt
        
        # Merge all profraw files
        llvm-profdata merge -sparse $(cat profraw_files.txt) -o merged.profdata
        
        # Find all test executables
        test_bins=$(find build/coverage -type f -executable -name "Test*" -o -name "*test*")
        
        # Build llvm-cov show command with all object files
        llvm_cov_cmd="llvm-cov show --show-branches=count --instr-profile=merged.profdata"
        first=true
        for bin in $test_bins; do
          if [ "$first" = true ]; then
            llvm_cov_cmd="$llvm_cov_cmd $bin"
            first=false
          else
            llvm_cov_cmd="$llvm_cov_cmd -object $bin"
          fi
        done
        
        # Generate coverage report
        eval "$llvm_cov_cmd" > coverage.txt

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        GITHUB_TOKEN: ${{ github.token }}
      with:
        args: >
          -Dproject.settings=.github/sonar/sonar-project.properties
          -Dsonar.cfamily.compile-commands=bw-output/compile_commands.json
          -Dsonar.cfamily.llvm-cov.reportPath=coverage.txt

