name: Generate Coverage Report
description: Generate code coverage report and post to PR if applicable

runs:
  using: composite
  steps:
    - name: Generate Coverage XML Report
      shell: bash
      run: |
        gcovr --root . \
          --filter 'source/.*' \
          --filter 'include/.*' \
          --exclude '.*/test/.*' \
          --gcov-ignore-parse-errors=negative_hits.warn_once_per_file \
          --cobertura coverage.xml \
          --json-summary coverage-summary.json \
          --print-summary

    - name: Generate Coverage Markdown Report
      # Generate code coverage summary markdown file (code-coverage-results.md)
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        format: markdown
        output: both

    - name: Generate Coverage PR Comment
      # Add sticky coverage comment to PRs
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: coverage
        recreate: true
        path: code-coverage-results.md

    - name: Generate Coverage Badge
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      shell: bash
      run: |
        echo "::group::Extract badge from CodeCoverageSummary markdown"
        BADGE_URL=$(grep -oP '!\[Code Coverage\]\(\K[^)]+' code-coverage-results.md | head -1)
        if [ -z "$BADGE_URL" ]; then
          echo "Error: Could not find badge URL in markdown"
          exit 1
        else
          echo "Found badge URL: $BADGE_URL"
        fi
        mkdir -p pages/coverage
        curl -s -o pages/coverage/coverage.svg "$BADGE_URL"
        echo "Badge saved to pages/coverage/coverage.svg"
        echo "::endgroup::"

    - name: Add Date to Coverage Report
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      shell: bash
      run: |
        echo "::group::Add generation date to coverage report"
        {
          cat code-coverage-results.md
          echo ""
          echo "---"
          echo "**Report generated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        } > code-coverage-dated-results.md
        echo "Date appended successfully"
        echo "::endgroup::"

    - name: Generate Coverage HTML Report
      # Convert markdown to HTML to update the github pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: wranders/markdown-to-pages-action@v1
      with:
        token: ${{ github.token }}
        files: code-coverage-dated-results.md
        out_path: pages/coverage
        out_path_not_empty: true
        title: "Code Coverage Report"

    - name: Upload Coverage Artifact to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: pages

    - name: Deploy Coverage Artifact to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v4
