name: CI Full (Mac Linux Windows Debug Release)

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
        build_type: [debug, release]

    uses: ./.github/workflows/ci-steps.yaml
    with:
      os: ${{ matrix.os }}
      build_type: ${{ matrix.build_type }}