name: CI Full (Mac-Linux-Windows Deb-Rel)

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        runner: [linux, mac, windows]
        build_type: [debug, release]

    uses: ./.github/workflows/ci-steps.yaml
    with:
      runner: ${{ matrix.runner }}
      build_type: ${{ matrix.build_type }}
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}