name: CI Minimal (Linux-Debug or choice)

on:
  pull_request:
  workflow_dispatch:
    inputs:
      os:
        description: 'Runner label to use'
        required: true
        default: 'macos-14'
        type: choice
        options: ['macos-14', 'ubuntu-24.04', 'windows-2022', 'apg-mac-001']
      build_type:
        description: 'CMake build type'
        required: true
        default: 'debug'
        type: choice
        options: ['debug', 'release']
      self_hosted:
        description: 'Is this self-hosted?'
        required: true
        default: 'false'
        type: choice
        options: ['true', 'false']

jobs:
  minimal-build:
    uses: ./.github/workflows/ci-steps.yaml
    with:
      os: ${{ github.event.inputs.os }}
      build_type: ${{ github.event.inputs.build_type }}
      self_hosted: 'true'
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}