name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      build_type:
        required: true
        type: string
      self_hosted:
        required: true
        type: string
    secrets:
      GH_PACKAGES_TOKEN:
        required: true

jobs:
  build:
    name: ${{ inputs.build_type }} build on ${{ inputs.self_hosted == 'true' && 'Self-Hosted-' || '' }}${{ inputs.os }}
    runs-on: 'self-hosted'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        lfs: true
        submodules: recursive
        fetch-depth: 0

    - name: Install required dependencies (Linux only)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libxmu-dev libxi-dev libgl-dev libxrandr-dev libxinerama-dev libxcursor-dev mono-complete

    - name: Install Mono if missing (macOS only)
      if: runner.os == 'macOS'
      run: |
        if ! command -v mono >/dev/null; then
          echo "Mono not found, installing with Homebrew..."
          brew install mono
        else
          echo "Mono already installed"
        fi

    - name: Setup compiler environment (Windows only)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup vcpkg caching via GitHub Packages
      uses: ./.github/actions/setup-vcpkg-cache
      with:
        os: ${{ runner.os }}
        gh-packages-token: ${{ secrets.GH_PACKAGES_TOKEN }}

    - name: Configure
      run: cmake --preset ${{ inputs.build_type }}

    - name: Build
      run: cmake --build --preset ${{ inputs.build_type }}

    # Unit tests still failing using pixar USD.
    - name: Test
      run: ctest --preset ${{ inputs.build_type }}

    - name: Upload vcpkg failure logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: vcpkg-build-logs
        path: externals/vcpkg/buildtrees