name: main

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux_Clang_11_Python37
          os: ubuntu-22.04
          compiler: clang
          compiler_version: "11"
          python: 3.7
          build_config: 'release'

        - name: MacOS_Xcode_15_Python37
          os: macos-14
          compiler: xcode
          compiler_version: "15.4"
          python: 3.7
          build_config: 'release'

        - name: Windows_VS2022_x64_Python37
          os: windows-2022
          architecture: x64
          python: 3.7
          build_config: 'release'

    steps:
    - name: Sync Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install xorg-dev
        if [ "${{ matrix.compiler_version }}" != 'None' ]; then
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++-${{ matrix.compiler_version }}
            echo "CC=gcc-${{ matrix.compiler_version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.compiler_version }}" >> $GITHUB_ENV
          else
            sudo apt-get install -y clang-${{ matrix.compiler_version }}
            echo "CC=clang-${{ matrix.compiler_version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.compiler_version }}" >> $GITHUB_ENV
          fi
        fi

    - name: Install Dependencies (MacOS)
      if: runner.os == 'macOS'
      run: |
        if [ "${{ matrix.compiler_version }}" != 'None' ]; then
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            brew install gcc@${{ matrix.compiler_version }}
            echo "CC=gcc-${{ matrix.compiler_version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.compiler_version }}" >> $GITHUB_ENV
          else
            ls -ls /Applications/
            sudo xcode-select -switch /Applications/Xcode_${{ matrix.compiler_version }}.app
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          fi
        fi

    - name: Install Python ${{ matrix.python }}
      if: matrix.python != 'None'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}

    - name: Install Python Dependencies
      if: matrix.python != 'None'
      run: pip install setuptools

    - name: CMake Generate
      run: cmake --preset ${{matrix.build_config}}

    - name: CMake Build
      run: cmake --build --preset ${{matrix.build_config}}

    - name: CMake Unit Tests
      run: ctest --preset ${{matrix.build_config}}
      working-directory: build

    
